// The set catalogue: the shipped snapshot of bitbusters.club's CC1 directory
// listing (public/sets.json, regenerated by `npm run refresh-sets`) plus the
// pure logic that turns a raw search query into a short, ordered result list.
//
// Everything here is deliberately free of DOM and network access so it can be
// unit-tested — main.ts owns the rendering.

export interface SetEntry {
  // Stable identifier and the .dat's filename without its extension.
  id: string;
  // What the player sees in the list.
  name: string;
}

export const SETS_INDEX_URL = "https://bitbusters.club/gliderbot/sets/cc1/";

// The one set bundled into the repo (public/intro.dat) rather than fetched, so
// the demo is playable with no network access at all.
export const INTRO_SET: SetEntry = { id: "Intro", name: "Intro" };

export interface CuratedSet extends SetEntry {
  label: string;
  blurb: string;
}

// Pinned above the search results. The first entry is what the hero's
// one-click "Play" button starts, so it must always be playable offline.
export const CURATED_SETS: readonly CuratedSet[] = [
  {
    id: "Intro",
    name: "Intro",
    label: "Intro",
    blurb: "A few gentle levels bundled with the demo. Works with no network at all.",
  },
  {
    id: "CC1",
    name: "CC1",
    label: "Chip's Challenge 1",
    blurb: "The original 149 levels from 1991 — the set the engine is verified against.",
  },
  {
    id: "CCLP1",
    name: "CCLP1",
    label: "Community Level Pack 1",
    blurb: "The first fan-made pack: 149 new levels in the classic style.",
  },
  {
    id: "CCLP2",
    name: "CCLP2",
    label: "Community Level Pack 2",
    blurb: "The second community pack, noticeably harder than CCLP1.",
  },
  {
    id: "CCLP3",
    name: "CCLP3",
    label: "Community Level Pack 3",
    blurb: "The third community pack — puzzles and design tricks turn up the difficulty.",
  },
  {
    id: "CCLP4",
    name: "CCLP4",
    label: "Community Level Pack 4",
    blurb: "The fourth community pack.",
  },
  {
    id: "CCLP5",
    name: "CCLP5",
    label: "Community Level Pack 5",
    blurb: "The fifth community pack.",
  },
];

export function datUrl(id: string): string {
  return `${SETS_INDEX_URL}${encodeURIComponent(id)}.dat`;
}

// The snapshot ships as { generatedAt, source, sets: string[] }. Anything else
// (a 404 HTML page, a truncated file) parses to an empty list rather than
// throwing, so a bad snapshot degrades to "Intro only" instead of a blank
// landing page.
export function parseSetsSnapshot(raw: unknown): SetEntry[] {
  const sets = (raw as { sets?: unknown } | null)?.sets;
  if (!Array.isArray(sets)) return [];
  const entries: SetEntry[] = [];
  for (const value of sets) {
    if (typeof value !== "string") continue;
    const id = value.trim();
    if (!id) continue;
    entries.push({ id, name: id });
  }
  return entries;
}

export interface SetSearchResult {
  matches: SetEntry[];
  // Total matches before `limit` was applied, so the UI can say
  // "showing 50 of 312".
  total: number;
}

// Case- and punctuation-insensitive so "cclp 1" and "cclp1" both find CCLP1.
function normalize(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "");
}

// Ordering: curated sets first (never filtered out of the catalogue, they're
// the recommended path), then prefix matches, then substring matches, each
// alphabetical. Uncapped by default — callers pass a limit when rendering.
export function searchSets(
  sets: readonly SetEntry[],
  query: string,
  limit = Infinity,
  curatedIds: readonly string[] = CURATED_SETS.map((s) => s.id),
): SetSearchResult {
  const needle = normalize(query);
  const curatedRank = new Map(curatedIds.map((id, i) => [id, i]));

  const ranked: { entry: SetEntry; rank: number }[] = [];
  for (const entry of sets) {
    const haystack = normalize(entry.id);
    const isCurated = curatedRank.has(entry.id);
    if (!needle) {
      // No query: the curated shelf is rendered separately, so the catalogue
      // starts with everything else in alphabetical order.
      if (isCurated) continue;
      ranked.push({ entry, rank: 1 });
      continue;
    }
    if (!haystack.includes(needle)) continue;
    const rank = isCurated ? 0 : haystack.startsWith(needle) ? 1 : 2;
    ranked.push({ entry, rank });
  }

  ranked.sort((a, b) => {
    if (a.rank !== b.rank) return a.rank - b.rank;
    const curatedA = curatedRank.get(a.entry.id);
    const curatedB = curatedRank.get(b.entry.id);
    if (curatedA !== undefined && curatedB !== undefined) return curatedA - curatedB;
    return a.entry.name.localeCompare(b.entry.name);
  });

  return {
    matches: ranked.slice(0, Number.isFinite(limit) ? limit : ranked.length).map((r) => r.entry),
    total: ranked.length,
  };
}
